package blog::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'blog::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:catalyst',
        user => 'root',
        password => '@Ya1381992',
        AutoCommit => q{1},
    }
);

=head1 NAME

blog::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<blog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<blog::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

aya

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
